"""Initial Migration

Revision ID: d9d81a44e756
Revises: 
Create Date: 2026-05-15 22:03:05.428947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d81a44e756'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('id_classroom', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_number', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_classroom')
    )
    op.create_table('professors',
    sa.Column('id_professor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_professor'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('schedules',
    sa.Column('id_schedule', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_code', sa.String(), nullable=False),
    sa.Column('reservation_date', sa.Date(), nullable=False),
    sa.Column('id_professor', sa.Integer(), nullable=False),
    sa.Column('id_classroom', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_classroom'], ['classrooms.id_classroom'], ),
    sa.ForeignKeyConstraint(['id_professor'], ['professors.id_professor'], ),
    sa.PrimaryKeyConstraint('id_schedule')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    op.drop_table('professors')
    op.drop_table('classrooms')
    # ### end Alembic commands ###
